services:
  mongo.db.patient:
    restart: always
    image: mongo:8.0-rc
    container_name: mongo.db.patient.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.patient.volume:/data/db
  mongo.db.patient.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.patient.ui
    ports:
      - 27032:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.patient:27017/
      ME_CONFIG_BASICAUTH: false 
volumes:
  mongo.db.patient.volume: